#!/usr/bin/env node

var caniuse, browsers = [
  'chrome 49',
  'edge 15',
  'firefox 51',
  'opera 36'
].join(', ');

try {
  caniuse = require('caniuse-api');
} catch(e) {
  console.log('module \x1B[1mcaniuse-api\x1B[0m not found');
  console.log('please install it via:');
  console.log('  npm i -g caniuse-api');
  process.exit(1);
}

switch (process.argv.length) {
  case 3:
    var found = [].concat(caniuse.find(process.argv[2]));
    found.forEach(function (feature) {
      console.log(feature + ': ' + (caniuse.isSupported(feature, browsers) ? '🍾 \x1B[1myup\x1B[0m 🎉' : 'nope'));
    });
    if (found.length < 1) console.log('I have no idea');
    break;
  default:
  console.log('you need to specify a feature name, example:');
  console.log('  caniuse class');
}
